---
title: "Lab_5"
author: "Julio F. Barahona Martinez"
date: "October 3, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("readr"))    {install.packages("readr");   library("readr")}
if (!require("dplyr"))    {install.packages("dplyr");   library("dplyr")}
if (!require("kableExtra"))    {install.packages("kableExtra");   library("kableExtra")}
if (!require("ggplot2"))    {install.packages("ggplot2");   library("ggplot2")}
if (!require("ggpubr"))    {install.packages("ggpubr");   library("ggpubr")}
if (!require("tidyverse"))    {install.packages("tidyverse");   library("tidyverse")}
if (!require("tidytext"))    {install.packages("tidytext");   library("tidytext")}
if (!require("RColorBrewer"))    {install.packages("RColorBrewer");   library("RColorBrewer")}
if (!require("gplots"))    {install.packages("gplots");   library("gplots")}
```

## Leyendo los datos
```{r reading_data, message=FALSE, warning=FALSE}
original_data <- read.csv("data/GrammarandProductReviews.csv", stringsAsFactors = TRUE)
```

## Analisis Explorativo

### Tipos de datos
```{r data }
types <- as.data.frame(colnames(original_data))
types$tipo <- sapply(original_data, class)
kable(types) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

### caja y bigotes de los datos numericos

Distribucion de percentiles
```{r prob_revies}
summary(original_data$reviews.rating)
quantile(original_data$reviews.rating, probs = c(0,.25,.5,.75,1))
```
  
```{r boxplot_diagrams warning=FALSE,message=FALSE,error=FALSE}
boxplot(original_data$reviews.rating ~ original_data$reviews.userProvince, main = 'Distribusion calificiones', ylab =  'Puntaje', las = 1)
```

Se puede observar que la mayoria de los puntajes estan de 3 para arriba (a nivel general) y se mantiene por provincia


## Analisis de palabras emotivas (frecuencia y proporcion)
```{r}
original_data$reviews.text <- as.character(original_data$reviews.text)

total_words_count <- original_data %>%
    unnest_tokens(word, reviews.text) %>%  
    anti_join(stop_words, by = "word") %>%                  
    filter(!grepl('[0-9]', word)) %>%
   left_join(get_sentiments("nrc"), by = "word") %>%                        
    group_by(brand) %>%
    summarize(total= n()) %>%
    ungroup()

emotion_words_count <- original_data %>% 
  unnest_tokens(word, reviews.text) %>%                           
  anti_join(stop_words, by = "word") %>%                  
  filter(!grepl('[0-9]', word)) %>%
  left_join(get_sentiments("nrc"), by = "word") %>%
  filter(!(sentiment == "negative" | sentiment == "positive" | sentiment == "NA")) %>%
  group_by(brand) %>%
  summarize(emotions= n()) %>%
  ungroup()

emotions_to_total_words <- total_words_count %>%
     left_join(emotion_words_count, by="brand") %>%
               mutate(percent_emotions=round((emotions/total)*100,1))
```


